// Generated by   : ImageConverter 565 Online
// Generated from : ttgo.jpg
// Time generated : Thu, 27 Jun 19 09:09:44 +0200  (Server timezone: CET)
// Image Size     : 240x135 pixels
// Memory usage   : 64800 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
#elif defined(__PIC32MX__)
    #define PROGMEM
#elif defined(__arm__)
    #define PROGMEM
#endif

const unsigned short ttgo[32400] PROGMEM={
0x8D7B, 0x8D9B, 0x8D9B, 0x959B, 0x959B, 0x959B, 0x959B, 0x959B, 0x8D9A, 0x8D9A, 0x8D7B, 0x8D7B, 0x8D7B, 0x8D7B, 0x8D7B, 0x8D7B,   // 0x0010 (16) pixels
};
